# Generated by Django 5.2.12 on 2026-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobooking',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-50', '1-50'), ('51-200', '51-200'), ('201-1k', '201-1k'), ('1k+', '1k+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='project_interest',
            field=models.CharField(blank=True, choices=[('CI/CD Optimization', 'CI/CD Optimization'), ('Infrastructure as Code', 'Infrastructure as Code'), ('Security Guardrails', 'Security Guardrails'), ('Developer Productivity', 'Developer Productivity')], default='CI/CD Optimization', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='project_type',
            field=models.CharField(blank=True, choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('design', 'UI/UX Design'), ('consulting', 'Consulting'), ('other', 'Other')], default='web', max_length=20, null=True),
        ),
    ]
