# Generated by Django 5.2.12 on 2026-03-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_demobooking_company_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demobooking',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='demobooking',
            name='project_interest',
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='preferred_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('design', 'UI/UX Design'), ('consulting', 'Consulting'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='core_api.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
